package Money;
import java.sql.*;

public class DBCon {
 
	public static Connection getCon()
	{
		Connection con=null;
		try
		{
			Class.forName("org.h2.Driver");
			con=DriverManager.getConnection("jdbc:h2:~/selavu_db;AUTO_SERVER=TRUE;MODE=Oracle", "sa", "");
			
			// Initialize tables if they don't exist
			try (Statement stmt = con.createStatement()) {
				stmt.execute("CREATE TABLE IF NOT EXISTS selavu_users (" +
						"uname VARCHAR(50) PRIMARY KEY, " +
						"email VARCHAR(100) UNIQUE NOT NULL, " +
						"upass VARCHAR(100) NOT NULL)");
						
				stmt.execute("CREATE TABLE IF NOT EXISTS selavu_expenses (" +
						"expense_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
						"uname VARCHAR(50) NOT NULL, " +
						"amount DECIMAL(10,2) NOT NULL, " +
						"iname VARCHAR(100) NOT NULL, " +
						"qty VARCHAR(50), " +
						"category VARCHAR(50) NOT NULL, " +
						"pdate DATE NOT NULL, " +
						"CONSTRAINT fk_user FOREIGN KEY (uname) REFERENCES selavu_users(uname))");
			}
		}
		catch(Exception e)
		{
			System.out.println(e);
		}
		return con;
	}
	
}
